### ISSUE TITLE
Who approved this to be a RC without WARNING us that this thing DESTROYS all existing apps

### ISSUE THREAD

**Issue by drophit** [NativeScript/theme#171] opened 2019-08-24 00:19 UTC
Who is leading this theme group? Whomever decided to release this POS without posting a DIRE WARNING that this theme 2.0 system is in NO WAY backwards compatible should be REMOVED from this group. Does Progress have any idea how BAD this is?

I cant even begin to list the bugs - your docs are THIN and even your attempt to intro compat mode MISSES the light theme and breaks ALL of the sample apps and templates.

Waoooowwww - I hope this is not a day job for anyone here :(

**Comment by NathanaelA** [comment] 2019-08-24 01:28
@drophit - Hi I have nothing to do with the Theme 2.0 system, nor am I related with Progress.    But you should tone done your gripe a lot. The community tries to be a very friendly  (Hi @etabakov   :grinning: ) place to be, and insulting people does not go over very well at all.  I realize you are very disappointed, and that it obviously didn't work for your apps.  First it is trivial to revert to v1.04 and  I guarantee everyone who has put in work on v2.0; has worked very hard on trying to make it work.      

It is also no longer RC, the RC is over a month old -- so if you used RC; you are using some really old code.  v2.06 was released yesterday is the latest of the 2.0 releases.    You can also still use v1.04 (which is what I use, because of https://github.com/NativeScript/theme/issues/157) 

So rather than complain, load up the issues with anything you find in 2.0 and they will work on fixing them so that a later 2.x will be better for everyone in the community.

**Comment by bundyo** [comment] 2019-08-25 06:15
Yes, 2.0 is still beta, and I consider it a mistake that it was released in the "latest" npm channel and not in "rc" for instance, as it wouldn't be auto-upgraded for people that use "latest" as their version in package.json. Other than that, it is stated that it is not backwards compatible. Compat styling is not finished, as you can see in the tracking issue #160.

**Comment by NathanaelA** [comment] 2019-08-25 08:15
@bundyo - If 2.0 isn't supposed to be latest; then just release another  1.0x  so that it can become the latest.  :D     I didn't realize that 2.0 was still a RC.

**Comment by bundyo** [comment] 2019-08-25 09:02
Yeah, this is a good idea and I'll move 2.x to @rc.

**Comment by etabakov** [comment] 2019-08-26 07:58
@drophit - first, be sure to follow our [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/CODE_OF_CONDUCT.md) moving forward. Offensive and disrespectful tone will not be tolerated. 

As @NathanaelA already explained - the latest version is a major one. It is not expected to be backward compatible and according to [semver](https://semver.org/) - breaking changes are to be expected. If you have any specific bugs that you think should be addressed - open a new issue with a proper description, steps to reproduce, and expected behavior. 

Also, the current version is stable and good enough for production usage. This was the reasoning to tag it as latest. There will be more bug fixes and features coming with the next versions (as with every piece of software), but the current state is the official version.

**Closed by etabakov** 2019-08-26 07:58 UTC
